# Generated by Django 6.0.6 on 2026-07-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imdb_rating', models.FloatField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster', models.URLField()),
                ('backdrop', models.URLField(blank=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
